***NUMPY***

It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types


* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically).
* Changing the size of an ndarray will create a new array and delete the original.

* The elements in a NumPy array are all required to be of the same data type

### Creating Numpy Arrays

In [ ]:
# np.array
import numpy as np #need to use np     #
c = np.array([1,2,3,4,5.0]) #1d array
print(c)

l=[1,2,3,4,'c']
print(l)


[1. 2. 3. 4. 5.]
[1, 2, 3, 4, 'c']


In [ ]:
# iterating through numpy arrays
print(c)
for i in c:
  print(i)

[1. 2. 3. 4. 5.]
1.0
2.0
3.0
4.0
5.0


In [ ]:
# iterating through 2D numpy arrays
b = np.array([[1,2,3],[4,5,6]])  #matrix
print(b)
print("___________________")
#for i in b:
 # print(i)
  #for i2 in i:
   # print(i2)
b[1][1]
print(type(b))


[[1 2 3]
 [4 5 6]]
___________________
<class 'numpy.ndarray'>


In [ ]:
c = np.array([[[1,2],[3,4]],[[3,4],[5,6]]])  #3d tensor   # 1d -> [] 2d ->[[],[]]  3d ->[[[],[]],[[],[]]]
c[1][1][0]


5

In [ ]:
for i in c:
  print(i)
  print("_____")
  for i2 in i:
    print(i2)
    for i3 in i2:
      print(i3)

[[1 2]
 [3 4]]
_____
[1 2]
1
2
[3 4]
3
4
[[3 4]
 [5 6]]
_____
[3 4]
3
4
[5 6]
5
6


In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])  #matrix
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3]])

In [ ]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# dtype
print(np.array([1,2,3],dtype=float))
print(np.array([10,-5,0],dtype=bool))  # 1 true 0 false 2,3 true
print(np.array([1,2,3],dtype=str))
print(np.array(['1','2','3'],dtype=int))

[1. 2. 3.]
[ True  True False]
['1' '2' '3']
[1 2 3]


In [ ]:
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
#arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
for i in range(1,11,2):
  print(i)

1
3
5
7
9


In [ ]:
# np.arange
np.arange(1,11,2)  # for i in range (1,12):

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape
q=np.arange(0,16).reshape(2,8)
print(q)
print(type(q))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
<class 'numpy.ndarray'>


In [ ]:
np.arange(0,8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.arange(0,5).reshape(1,5)   # 5 divisible by 1 and 5   6 is divisible by 2,3,6

array([[0, 1, 2, 3, 4]])

In [ ]:
l=[1,2,3,4,5,0]

In [ ]:
c=np.array([[0, 1, 2], [3, 4, 5]])
print(c)


[[0 1 2]
 [3 4 5]]


In [ ]:
c=np.arange(0,6).reshape(3,2)
print(c)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
np.arange(0,8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

26 th june

In [ ]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2) #.reshape(2,2,2)  no of elements/no of rows = no of cols 2*4=8  2*2*2=8

print(a1)
print(a2)
print(a3)



[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
print(a1)
a1[0:6:2]   #output= 0,2,4
a1[0:6]


[0 1 2 3 4 5 6 7 8 9]


array([0, 2, 4])

In [ ]:
c=np.arange(0,6).reshape(3,2)
print(c)

c[0:2,1]   #2x2  [[0,1],[2,3],[4,5]]


[[0 1]
 [2 3]
 [4 5]]


array([1, 3])

In [ ]:
c=np.arange(12).reshape(4,3)
print(c)
#c[0:3:2]
#c[0:3:2,:]
c[0:3:2,0::2]
#c[0:3,1]        # output =1 4 7
#c[0:3,0:2]


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[0, 2],
       [6, 8]])

In [ ]:
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 4,  7],
       [ 8, 11]])

28 th june

In [ ]:
import numpy as np
a3 = np.arange(8).reshape(2,2,2)
print(a3)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
q=a3[1]
print(q)
q[1,1]

[[4 5]
 [6 7]]


7

In [ ]:
a3[1,1,1]

7

In [ ]:
a4=np.arange(27).reshape(3,3,3)
print(a4)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
a4[2,1,1]


22

In [ ]:
a4[0:2,2]                            #[   [[0,1,2],[3,4,5],[6,7,8]],    [[9,10,11],[12,13,14],[15,16,17]],   [[18,19,20],[21,22,23],[24,25,26]]     ]
                                    #               0                                 1                                       2

array([[ 6,  7,  8],
       [15, 16, 17]])

In [ ]:
a4[0:2,0,0::2]

array([[ 0,  2],
       [ 9, 11]])

In [ ]:
a4[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a4[0,1]

array([3, 4, 5])

In [ ]:
a4[1,:,1]

array([10, 13, 16])

In [ ]:
a4[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

29 th june

In [ ]:
# np.ones and np.zeros
import numpy as np
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# np.random
q=np.random.random(5)
q

array([0.60086498, 0.16934289, 0.85462004, 0.82248688, 0.35127591])

In [ ]:
np.random.randint(1, size=10,high=5)


array([4, 4, 4, 3, 4, 1, 1, 2, 1, 3])

In [ ]:
a=np.arange(10)
print(a)
b=np.random.choice(a,10,replace=False)     #np.random.choice(a, size=None, replace=True, p=None)
print(b)
c=np.random.choice(a,11,replace=True)     #np.random.choice(a, size=None, replace=True, p=None)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[1 5 0 9 3 7 6 8 2 4]
[6 6 9 0 2 8 0 2 0 6 8]


In [ ]:
np.array(q,dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# np.linspace
np.linspace(1,10,5,dtype=str)                      #1 to 10

array(['1.0', '3.25', '5.5', '7.75', '10.0'], dtype='<U32')

In [ ]:
np.linspace(-10,10,10,dtype=float)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# np.identity
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Array Attributes

In [ ]:
a1 = np.arange(10,dtype=int)
print(a1)
a2 = np.arange(12,dtype=float).reshape(3,4)
print(a2)
a3 = np.arange(8).reshape(2,2,2)
print(a3)



[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# ndim
print(a3.ndim)
print(a2.ndim)
print(a1.ndim)

3
2
1


In [ ]:
# shape
print(a1.shape)


(10,)


In [ ]:
# size
print(a3.size)
a3

8


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int64
float64
int64


### Changing Datatype

In [ ]:
# astype
a3 = np.arange(8).reshape(2,2,2)
print(a3)
print(a3.astype(str))

print(type(a3))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[['0' '1']
  ['2' '3']]

 [['4' '5']
  ['6' '7']]]
<class 'numpy.ndarray'>


### Array Operations  (imporant)

In [ ]:
import numpy as np

a1 = np.arange(15).reshape(3,5)
a2 = np.arange(15,30).reshape(3,5)

print(a1)
print(a2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [ ]:
# scalar operations

# arithmetic
print(a1)
#0/2=

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
print(a1 + 2)    # matrix + scalar

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]


In [ ]:
print(a1 - 2)


[[-2 -1  0  1  2]
 [ 3  4  5  6  7]
 [ 8  9 10 11 12]]


In [ ]:
print(a1 / 2)  #1/2 =0.5


[[0.  0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4.  4.5]
 [5.  5.5 6.  6.5 7. ]]


In [ ]:
print(a1 % 2)

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


In [ ]:
print(a1 * 2)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


In [ ]:
print(a1 ** 2)

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]


In [ ]:
# relational
a2 = np.arange(15,30).reshape(3,5)
print(a2)
print(a2 > 15)


[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [ ]:
print(a2 == 17)
print(a2 !=17)

[[False False  True False False]
 [False False False False False]
 [False False False False False]]
[[ True  True False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [ ]:
# vector operations
print(a1)
print(a2)
a1+a2

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


array([[15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43]])

In [ ]:
a1-a2
a4=np.arange(0,15).reshape(3,5)
print(a4)
a5=np.random.randint(66,300,size=(3,5))
print(a5)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[245  94 142 118  87]
 [286 212  93 251 172]
 [117 145 294 143 245]]


In [ ]:
a5-a4

array([[245,  93, 140, 115,  83],
       [281, 206,  86, 243, 163],
       [107, 134, 282, 130, 231]])

### Array Functions

In [2]:
import numpy as np


In [14]:

a2=np.random.rand(5)
print(a2)
a2 = np.round(a2,1)
print(a2)

[0.74673567 0.78284845 0.47550231 0.4464171  0.82909323]
[0.7 0.8 0.5 0.4 0.8]


In [15]:
a1 = np.random.randint(1,3,(3,5))
print(a1)

[[2 2 2 1 1]
 [2 1 2 1 1]
 [1 2 1 2 2]]


In [18]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=1)

array([8, 4, 8])

In [19]:
np.prod(a1,axis=1)

array([8, 4, 8])

In [23]:
np.sum(a1,axis=1)

array([8, 7, 8])

In [22]:
np.sum(a1,axis=0)

array([5, 5, 5, 4, 4])

In [31]:
# mean/median/std/var
print(a1)
#np.mean(a1,axis=1)
#np.var(a1,axis=1)  #variance
#np.median(a1,axis=1)
np.mean(a1,axis=0)


[[2 2 2 1 1]
 [2 1 2 1 1]
 [1 2 1 2 2]]


array([1.66666667, 1.66666667, 1.66666667, 1.33333333, 1.33333333])

very important

In [37]:
# dot product
a2 = np.arange(4).reshape(2,2)
a3 = np.arange(4,8).reshape(2,2)
print(a2)
print(a3)

print("dot function",np.dot(a2,a3))
print("*",a2*a3)  # dont use it for matrix multiplicaton

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
dot function [[ 6  7]
 [26 31]]
* [[ 0  5]
 [12 21]]


In [41]:
# round/floor/ceil
q=np.random.random((2,3))*100
print(q)
print("round")
print(np.round(q))
print("ceil")
print(np.ceil(q))
print("floor")
print(np.floor(q))


[[54.17898771 55.84687359 49.38800195]
 [92.43380791 25.98231244 28.68476383]]
round
[[54. 56. 49.]
 [92. 26. 29.]]
ceil
[[55. 56. 50.]
 [93. 26. 29.]]
floor
[[54. 55. 49.]
 [92. 25. 28.]]
